libpcc: BinaryFile Class Reference
BinaryFile Class Reference
#include <BinaryFile.hpp>
Public Member Functions
BinaryFile ()
BinaryFile (const char *data, size_t size)
BinaryFile (zmq::message_t &msg)
~BinaryFile ()
zmq::message_t get () const
const char * getData () const
long getSize () const
void set (const char *data, size_t size)
void set (zmq::message_t &msg)
void copy (char *data, size_t size) const
void copy (char *data) const
bool read (const std::string &file_path)
bool write (const std::string &file_path)
Static Public Member Functions
static bool read (const std::string &file_path, char *&data, long &size)
static bool write (const std::string &file_path, const char *data, long size)
Private Attributes
char * data_
long size_
Detailed Description
Wrapper for binary file read and write functionality. Can be used to store and extract compressed and uncompressed point cloud data.
Definition at line 12 of file BinaryFile.hpp.
Constructor & Destructor Documentation
BinaryFile::BinaryFile ()
Definition at line 6 of file BinaryFile.cpp.
     : data_(nullptr)
     , size_(-1)
 {}
BinaryFile::BinaryFile (const char * data, size_t size)
Definition at line 11 of file BinaryFile.cpp.
     : data_(nullptr)
     , size_(-1)
 {
     set(data, size);
 }
BinaryFile::BinaryFile (zmq::message_t & msg) explicit
Definition at line 18 of file BinaryFile.cpp.
     : data_(nullptr)
     , size_(-1)
 {
     set(msg);
 }
BinaryFile::~BinaryFile ()
Definition at line 25 of file BinaryFile.cpp.
References data_.
 {
     if(data_ != nullptr)
         delete [] data_;
 }
Member Function Documentation
zmq::message_t BinaryFile::get () const
Definition at line 31 of file BinaryFile.cpp.
References copy(), and size_.
{
     if (size_ == -1)
         return zmq::message_t();
     zmq::message_t msg(static_cast<size_t>(size_));
     copy((char*) msg.data(), msg.size());
     return msg;
 }
const char * BinaryFile::getData () const
Definition at line 41 of file BinaryFile.cpp.
References data_.
Referenced by copy().
 {
     return data_;
 }
long BinaryFile::getSize () const
Definition at line 46 of file BinaryFile.cpp.
References size_.
Referenced by copy(), and main().
 {
     return size_;
 }
void BinaryFile::set (const char * data, size_t size)
Definition at line 51 of file BinaryFile.cpp.
References data_, and size_.
 {
     if(data_ != nullptr)
         delete [] data_;
     data_ = new char[size];
     memcpy(data_, data, size);
     size_ = size;
 }
void BinaryFile::set (zmq::message_t & msg)
Definition at line 60 of file BinaryFile.cpp.
 {
     set((const char*) msg.data(), msg.size());
 }
void BinaryFile::copy (char * data, size_t size) const
Definition at line 65 of file BinaryFile.cpp.
References getData().
Referenced by copy(), get(), and main().
 {
     memcpy(data, getData(), size);
 }
void BinaryFile::copy (char * data) const
Definition at line 70 of file BinaryFile.cpp.
References copy(), getSize(), and size_.
 {
     if(size_ < 0)
         return;
     return copy(data, static_cast<size_t>(getSize()));
 }
bool BinaryFile::read (const std::string & file_path, char *& data, long & size) static
Definition at line 77 of file BinaryFile.cpp.
Referenced by main(), and read().
 {
     std::ifstream file(file_path, std::ifstream::binary);
     file.seekg(0, file.end);
     size = file.tellg();
     file.seekg(0, file.beg);
     if(size == -1)
         return false;
     delete [] data;
     data = new char[size];
     file.read(reinterpret_cast<char*>(data), size);
     return file ? true : false;
 }
bool BinaryFile::write (const std::string & file_path, const char * data, long size) static
Definition at line 96 of file BinaryFile.cpp.
Referenced by write().
 {
     std::ofstream file(file_path, std::ofstream::binary);
     file.write(data, size);
     return file ? true : false;
 }
bool BinaryFile::read (const std::string & file_path)
Definition at line 105 of file BinaryFile.cpp.
References data_, read(), and size_.
 {
     return BinaryFile::read(file_path, data_, size_);
 }
bool BinaryFile::write (const std::string & file_path)
Definition at line 110 of file BinaryFile.cpp.
References data_, size_, and write().
 {
     return BinaryFile::write(file_path, data_, size_);
 }
Member Data Documentation
char* BinaryFile::data_ private
Definition at line 36 of file BinaryFile.hpp.
Referenced by getData(), read(), set(), write(), and ~BinaryFile().
long BinaryFile::size_ private
Definition at line 37 of file BinaryFile.hpp.
Referenced by copy(), get(), getSize(), read(), set(), and write().
The documentation for this class was generated from the following files:
include/BinaryFile.hpp
src/BinaryFile.cpp