libpcc: BitVecArray Class Reference
BitVecArray Class Reference
#include <BitVecArray.hpp>
Public Member Functions
BitVecArray (BitCount t_NX=BIT_8, BitCount t_NY=BIT_8, BitCount t_NZ=BIT_8)
~BitVecArray ()
size_t getBitSize () const
size_t getByteSize () const
BitCount getNX () const
BitCount getNY () const
BitCount getNZ () const
void init (BitCount t_NX, BitCount t_NY, BitCount t_NZ)
Vec< uint64_t > const & operator[] (unsigned i) const
Vec< uint64_t > & operator[] (unsigned i)
void unpack (unsigned char *packed_data, size_t num_elmnts)
unsigned char * pack ()
void push_back (const Vec< uint64_t > &v)
void emplace_back (uint64_t x, uint64_t y, uint64_t z)
unsigned size () const
void resize (unsigned s)
void clear ()
Static Public Member Functions
static size_t getBitSize (size_t num_elmnts, BitCount nx, BitCount ny, BitCount nz)
static size_t getByteSize (size_t num_elmnts, BitCount nx, BitCount ny, BitCount nz)
Private Attributes
std::vector< Vec< uint64_t > > data_
BitCount nx_
BitCount ny_
BitCount nz_
Detailed Description
Container storing vector of BitVec instances with similar component precisions.
Definition at line 11 of file BitVecArray.hpp.
Constructor & Destructor Documentation
BitVecArray::BitVecArray (BitCount t_NX = BIT_8, BitCount t_NY = BIT_8, BitCount t_NZ = BIT_8) explicit
Definition at line 3 of file BitVecArray.cpp.
         : data_()
         , nx_(t_NX)
         , ny_(t_NY)
         , nz_(t_NZ)
 {}
BitVecArray::~BitVecArray ()
Definition at line 10 of file BitVecArray.cpp.
 {}
Member Function Documentation
size_t BitVecArray::getBitSize (size_t num_elmnts, BitCount nx, BitCount ny, BitCount nz) static
Returns the exact count of BITS needed to express num_elements of BitVec type with given x, y & z - component precision.
Definition at line 13 of file BitVecArray.cpp.
 {
     return num_elmnts * (nx+ny+nz);
 }
size_t BitVecArray::getBitSize () const
Returns the exact count of BITS needed to express all BitVec elements maintained by this instance.
Definition at line 18 of file BitVecArray.cpp.
References data_, nx_, ny_, and nz_.
Referenced by getByteSize().
 {
     return BitVecArray::getBitSize(data_.size(), nx_, ny_, nz_);
 }
size_t BitVecArray::getByteSize (size_t num_elmnts, BitCount nx, BitCount ny, BitCount nz) static
Returns the exact count of BYTES needed to express num_elements of BitVec type with given x, y & z - component precision.
Definition at line 23 of file BitVecArray.cpp.
References getBitSize().
Referenced by PointCloudGridEncoder::decodeCell(), and PointCloudGridEncoder::encodeCell().
 {
     return static_cast<size_t>(ceil(getBitSize(num_elmnts, nx, ny, nz)/8.0f));
 }
size_t BitVecArray::getByteSize () const
Returns the exact count of BYTES needed to express all BitVec elements maintained by this instance.
Definition at line 28 of file BitVecArray.cpp.
References getBitSize().
Referenced by PointCloudGridEncoder::calcMessageSize(), PointCloudGridEncoder::decodePointCloudGrid(), PointCloudGridEncoder::encodePointCloudGrid(), pack(), and unpack().
 {
     return static_cast<size_t>(ceil(getBitSize()/8.0f));
 }
BitCount BitVecArray::getNX () const
Returns the x-component precision uniform among all BitVec elements maintained by this instance.
Definition at line 33 of file BitVecArray.cpp.
References nx_.
Referenced by PointCloudGridEncoder::extractPointCloudFromGrid(), and PointCloudGrid::getQuantizationStepSize().
 {
     return nx_;
 }
BitCount BitVecArray::getNY () const
Returns the y-component precision uniform among all BitVec elements maintained by this instance.
Definition at line 38 of file BitVecArray.cpp.
References ny_.
Referenced by PointCloudGridEncoder::extractPointCloudFromGrid(), and PointCloudGrid::getQuantizationStepSize().
 {
     return ny_;
 }
BitCount BitVecArray::getNZ () const
Returns the z-component precision uniform among all BitVec elements maintained by this instance.
Definition at line 43 of file BitVecArray.cpp.
References nz_.
Referenced by PointCloudGridEncoder::extractPointCloudFromGrid(), and PointCloudGrid::getQuantizationStepSize().
 {
     return nz_;
 }
void BitVecArray::init (BitCount t_NX, BitCount t_NY, BitCount t_NZ)
Sets the uniform x, y & z - component precision for BitVec elements maintained by this instance. Note: All existing data will be cleared if any given BitCount differs from existing setting.
Definition at line 48 of file BitVecArray.cpp.
References clear(), nx_, ny_, and nz_.
Referenced by GridCell::initColors(), and GridCell::initPoints().
 {
     clear();
     if(nx_ == t_NX && ny_ == t_NY && nz_ == t_NZ)
         return;
     nx_ = t_NX;
     ny_ = t_NY;
     nz_ = t_NZ;
 }
Vec< uint64_t > const & BitVecArray::operator[] (unsigned i) const
Returns element i in data_
Definition at line 58 of file BitVecArray.cpp.
References data_.
 {
     return data_[i];
 }
Vec< uint64_t > & BitVecArray::operator[] (unsigned i)
Returns element i in data_
Definition at line 63 of file BitVecArray.cpp.
References data_.
 {
     return data_[i];
 }
void BitVecArray::unpack (unsigned char * packed_data, size_t num_elmnts)
Fills list of BitVec elements from packed_data. num_elements should hold the total number of BitVec elements encoded by packed_data.
Definition at line 68 of file BitVecArray.cpp.
References data_, getByteSize(), BitVec::getXInt(), BitVec::getYInt(), BitVec::getZInt(), nx_, ny_, nz_, BitVec::setX(), BitVec::setY(), and BitVec::setZ().
Referenced by PointCloudGridEncoder::decodeCell().
 {
     data_.clear();
     data_.resize(num_elmnts);
     size_t elmt_idx = 0;
     size_t elmt_size = nx_+ny_+nz_;
     size_t current_bit = 0;
     std::bitset<8> byte;
     BitVec bit_vec(0,0,0,nx_,ny_,nz_);
     for(size_t i = 0; i < getByteSize(); ++i) {
         byte = std::bitset<8>(static_cast<ulong>(packed_data[i]));
         for(size_t byte_idx = 0; byte_idx < byte.size(); ++byte_idx) {
             if(current_bit < nx_) {
                 bit_vec.setX(current_bit, byte[byte_idx]);
             }
             else if(current_bit < nx_+ny_) {
                 bit_vec.setY(current_bit-nx_, byte[byte_idx]);
             }
             else {
                 bit_vec.setZ(current_bit-nx_-ny_, byte[byte_idx]);
             }
             current_bit = (current_bit + 1) % elmt_size;
             if(current_bit == 0) {
                 data_[elmt_idx].x = bit_vec.getXInt();
                 data_[elmt_idx].y = bit_vec.getYInt();
                 data_[elmt_idx].z = bit_vec.getZInt();
                 elmt_idx++;
                 if(elmt_idx == data_.size())
                     break;
             }
         }
         if(elmt_idx == data_.size())
             break;
     }
 }
unsigned char * BitVecArray::pack ()
Returns a byte array of minimum size encoding all BitVec elements maintained by this instance.
Definition at line 105 of file BitVecArray.cpp.
References data_, AbstractBitValue::getBit(), getByteSize(), BitVec::getX(), BitVec::getY(), BitVec::getZ(), nx_, ny_, nz_, BitVec::setX(), BitVec::setY(), and BitVec::setZ().
Referenced by PointCloudGridEncoder::encodeCell().
 {
     auto* packed_data = new unsigned char[getByteSize()];
     std::bitset<8> byte;
     size_t current_byte = 0;
     size_t bit_idx = 0;
     BitVec bit_vec(0,0,0,nx_,ny_,nz_);
     // Pack all BitVec
     for(auto v: data_) {
         // convert x,y,z (uint64_t) to bit string
         bit_vec.setX(v.x);
         bit_vec.setY(v.y);
         bit_vec.setZ(v.z);
         // pack x-component
         for(size_t i = 0; i < nx_; ++i) {
             byte[bit_idx] = bit_vec.getX()->getBit(i);
             bit_idx = (bit_idx + 1) % 8;
             if(bit_idx == 0) {
                 packed_data[current_byte] = static_cast<unsigned char>(byte.to_ulong());
                 ++current_byte;
             }
         }
         // pack y-component
         for(size_t i = 0; i < ny_; ++i) {
             byte[bit_idx] = bit_vec.getY()->getBit(i);
             bit_idx = (bit_idx + 1) % 8;
             if(bit_idx == 0) {
                 packed_data[current_byte] = static_cast<unsigned char>(byte.to_ulong());
                 ++current_byte;
             }
         }
         // pack z-component
         for(size_t i = 0; i < nz_; ++i) {
             byte[bit_idx] = bit_vec.getZ()->getBit(i);
             bit_idx = (bit_idx + 1) % 8;
             if(bit_idx == 0) {
                 packed_data[current_byte] = static_cast<unsigned char>(byte.to_ulong());
                 ++current_byte;
             }
         }
     }
     // add padding for last byte if necessary
     if(bit_idx != 0) {
         while(bit_idx != 0) {
             byte[bit_idx] = false;
             bit_idx = (bit_idx + 1) % 8;
         }
         packed_data[current_byte] = static_cast<unsigned char>(byte.to_ulong());
     }
     return packed_data;
 }
void BitVecArray::push_back (const Vec< uint64_t > & v)
Appends aN element to data_. Note: component values in v should be expressible by x, y & z - component precision set for this instance.
Definition at line 159 of file BitVecArray.cpp.
References data_.
 {
     data_.push_back(v);
 }
void BitVecArray::emplace_back (uint64_t x, uint64_t y, uint64_t z)
Appends an element to data_ value set from input parameters. Note: component values in v should be expressible by x, y & z - component precision set for this instance.
Definition at line 164 of file BitVecArray.cpp.
References data_.
Referenced by GridCell::addVoxel().
 {
     data_.emplace_back(x,y,z);
 }
unsigned BitVecArray::size () const
Returns the current number of elements in data_.
Definition at line 169 of file BitVecArray.cpp.
References data_.
Referenced by GridCell::size().
 {
     return static_cast<unsigned>(data_.size());
 }
void BitVecArray::resize (unsigned s)
Resizes the container used to store BitVec instances.
Definition at line 174 of file BitVecArray.cpp.
References data_.
Referenced by PointCloudGridEncoder::decodeCell(), and GridCell::resize().
 {
     data_.resize(s);
 }
void BitVecArray::clear ()
Removes all BitVec instances maintained by this instance.
Definition at line 179 of file BitVecArray.cpp.
References data_.
Referenced by GridCell::clear(), and init().
 {
     data_.clear();
 }
Member Data Documentation
std::vector<Vec<uint64_t> > BitVecArray::data_ private
Definition at line 121 of file BitVecArray.hpp.
Referenced by clear(), emplace_back(), getBitSize(), operator[](), pack(), push_back(), resize(), size(), and unpack().
BitCount BitVecArray::nx_ private
Definition at line 122 of file BitVecArray.hpp.
Referenced by getBitSize(), getNX(), init(), pack(), and unpack().
BitCount BitVecArray::ny_ private
Definition at line 123 of file BitVecArray.hpp.
Referenced by getBitSize(), getNY(), init(), pack(), and unpack().
BitCount BitVecArray::nz_ private
Definition at line 124 of file BitVecArray.hpp.
Referenced by getBitSize(), getNZ(), init(), pack(), and unpack().
The documentation for this class was generated from the following files:
include/BitVecArray.hpp
src/BitVecArray.cpp