libpcc: Measure Class Reference
Measure Class Reference
#include <Measure.hpp>
Classes
struct ComparisonResult
Public Types
typedef std::chrono::system_clock Clock
typedef std::chrono::time_point< Clock > TimePoint
typedef std::chrono::milliseconds Milliseconds
Public Member Functions
Measure ()
~Measure ()
void startWatch ()
std::time_t stopWatch ()
Static Public Member Functions
static Measure::TimePoint now ()
static std::time_t span (Measure::TimePoint, Measure::TimePoint)
static void print (std::time_t)
static void print (const Measure::ComparisonResult &)
static const ComparisonResult compare (std::vector< UncompressedVoxel > const &p1, std::vector< UncompressedVoxel > const &p2, BoundingBox const &bb)
static float colorErrorYuv (const Vec< float > &, const Vec< float > &)
static float colorErrorYuv (const UncompressedVoxel &v1, const UncompressedVoxel &v2)
static float colorErrorYuvWithoutY (const Vec< float > &, const Vec< float > &)
static float colorErrorYuvWithoutY (const UncompressedVoxel &v1, const UncompressedVoxel &v2)
static float colorErrorCielab (const Vec< float > &, const Vec< float > &)
static float colorErrorCielab (const UncompressedVoxel &v1, const UncompressedVoxel &v2)
static float colorErrorXyz (const Vec< float > &, const Vec< float > &)
static float colorErrorXyz (const UncompressedVoxel &v1, const UncompressedVoxel &v2)
static float calcVariance (const std::vector< float > &)
Private Attributes
Measure::TimePoint start_time_
Detailed Description
Wraps simple time measurement tasks and provides a static interface to compare point clouds (points & colors).
Definition at line 16 of file Measure.hpp.
Member Typedef Documentation
typedef std::chrono::system_clock Measure::Clock
Definition at line 40 of file Measure.hpp.
typedef std::chrono::time_point<Clock> Measure::TimePoint
Definition at line 41 of file Measure.hpp.
typedef std::chrono::milliseconds Measure::Milliseconds
Definition at line 42 of file Measure.hpp.
Constructor & Destructor Documentation
Measure::Measure ()
Definition at line 3 of file Measure.cpp.
   : start_time_()
 {}
Measure::~Measure ()
Definition at line 7 of file Measure.cpp.
 {}
Member Function Documentation
void Measure::startWatch ()
Starts the internal watch of this instance.
Definition at line 37 of file Measure.cpp.
References start_time_.
Referenced by PointCloudGridEncoder::buildPointCloudGrid(), PointCloudGridEncoder::decodePointCloudGrid(), PointCloudGridEncoder::encodePointCloudGrid(), PointCloudGridEncoder::entropyCompression(), PointCloudGridEncoder::entropyDecompression(), and PointCloudGridEncoder::extractPointCloudFromGrid().
 {
     start_time_ = std::chrono::time_point_cast<Milliseconds>(Clock::now());
 }
std::time_t Measure::stopWatch ()
Stops the internal watch of this instance and returns the time difference since starting.
Definition at line 42 of file Measure.cpp.
References start_time_.
Referenced by PointCloudGridEncoder::buildPointCloudGrid(), PointCloudGridEncoder::decodePointCloudGrid(), PointCloudGridEncoder::encodePointCloudGrid(), PointCloudGridEncoder::entropyCompression(), PointCloudGridEncoder::entropyDecompression(), and PointCloudGridEncoder::extractPointCloudFromGrid().
 {
     TimePoint time_point = std::chrono::time_point_cast<Milliseconds>(Clock::now());;
     return std::chrono::duration_cast<Milliseconds>(time_point - start_time_).count();
 }
Measure::TimePoint Measure::now () static
Returns a timestamp to current time (in milliseconds).
Definition at line 10 of file Measure.cpp.
 {
     return std::chrono::time_point_cast<Milliseconds>(Clock::now());
 }
std::time_t Measure::span (Measure::TimePoint start_point, Measure::TimePoint end_point) static
Returns the time difference between given time_points (in milliseconds).
Definition at line 15 of file Measure.cpp.
 {
     return std::chrono::duration_cast<Milliseconds>(end_point - start_point).count();
 }
void Measure::print (std::time_t period_time) static
Prints given timestamp.
Definition at line 20 of file Measure.cpp.
 {
     std::cout << "TimePeriod Value (in seconds): " << period_time / 1000 << std::endl;
     std::cout << "TimePeriod Value (in milliseconds): " << period_time  << std::endl;
 }
void Measure::print (const Measure::ComparisonResult & data) static
Prints given Measure::ComparisonResult.
Definition at line 26 of file Measure.cpp.
References Measure::ComparisonResult::avg_clr_error, Measure::ComparisonResult::avg_pos_error, Measure::ComparisonResult::clr_variance, Measure::ComparisonResult::max_clr_error, Measure::ComparisonResult::max_pos_error, and Measure::ComparisonResult::pos_variance.
 {
     std::cout << "PC Differences " << std::endl;
     std::cout << "  > average position error " << data.avg_pos_error << std::endl;
     std::cout << "  > average color error " << data.avg_clr_error << std::endl;
     std::cout << "  > position variance " << data.pos_variance << std::endl;
     std::cout << "  > color variance " << data.clr_variance << std::endl;
     std::cout << "  > max position error " << data.max_pos_error << std::endl;
     std::cout << "  > max color error " << data.max_clr_error << std::endl;
 }
const Measure::ComparisonResult Measure::compare (std::vector< UncompressedVoxel > const & p1, std::vector< UncompressedVoxel > const & p2, BoundingBox const & bb) static
Finds closest voxel in p2 for each voxel in p1. Distances are then stored For each closest distance a color error is computed and stored. Average, variance and max is returned for point and color errors. Result is wrapped in Measure::ComparisonResult struct.
Definition at line 48 of file Measure.cpp.
References Measure::ComparisonResult::avg_clr_error, Measure::ComparisonResult::avg_pos_error, calcVariance(), Measure::ComparisonResult::clr_variance, colorErrorCielab(), BoundingBox::contains(), Measure::ComparisonResult::max_clr_error, Measure::ComparisonResult::max_pos_error, and Measure::ComparisonResult::pos_variance.
 {
     std::vector<float> min_distances(p1.size());
     std::vector<float> color_errors(p1.size());
 #pragma omp parallel for
     for(int p1_idx = 0; p1_idx < p1.size(); ++p1_idx) {
         if(!bb.contains(p1[p1_idx].pos))
             continue;
         float closest_distance = 100000;
         float clr_error = 0;
         for(auto p2_voxel : p2) {
             if(!bb.contains(p2_voxel.pos))
                 continue;
             float x_dist = (p1[p1_idx].pos[0] - p2_voxel.pos[0]) *
                            (p1[p1_idx].pos[0] - p2_voxel.pos[0]);
             float y_dist = (p1[p1_idx].pos[1] - p2_voxel.pos[1]) *
                            (p1[p1_idx].pos[1] - p2_voxel.pos[1]);
             float z_dist = (p1[p1_idx].pos[2] - p2_voxel.pos[2]) *
                            (p1[p1_idx].pos[2] - p2_voxel.pos[2]);
             auto distance = static_cast<float>(sqrt(x_dist + y_dist + z_dist));
             if(distance < closest_distance) {
                 closest_distance = distance;
                 clr_error = colorErrorCielab(p1[p1_idx], p2_voxel);
             }
         }
         min_distances[p1_idx] = closest_distance;
         color_errors[p1_idx] = clr_error;
     }
     float max_pos_error = 0;
     float avg_pos_error = 0;
     for(auto const& l : min_distances) {
         avg_pos_error += l;
         if(max_pos_error < l)
             max_pos_error = l;
     }
     avg_pos_error = avg_pos_error / min_distances.size();
     float max_clr_error = 0;
     float avg_clr_error = 0;
     for(auto const& k : color_errors) {
         avg_clr_error += k;
         if(max_clr_error < k) {
             max_clr_error = k;
         }
     }
     avg_clr_error = avg_clr_error / color_errors.size();
     float pos_variance = calcVariance(min_distances);
     float clr_variance = calcVariance(color_errors);
     ComparisonResult data;
     data.avg_pos_error = avg_pos_error;
     data.pos_variance = pos_variance;
     data.max_pos_error = max_pos_error;
     data.avg_clr_error = avg_clr_error;
     data.clr_variance = clr_variance;
     data.max_clr_error = max_clr_error;
     return data;
 }
float Measure::colorErrorYuv (const Vec< float > & point1, const Vec< float > & point2) static
Computes color error in YUV space. Values should be given in RGB space with component values in range [0,1].
Definition at line 112 of file Measure.cpp.
References Encoder::rgbToYuv(), Vec< C >::x, Vec< C >::y, and Vec< C >::z.
Referenced by colorErrorYuv().
 {
     Vec<float> point1_yuv = Encoder::rgbToYuv(point1);
     Vec<float> point2_yuv = Encoder::rgbToYuv(point2);
     float color_y = (point1_yuv.x - point2_yuv.x) * (point1_yuv.x - point2_yuv.x);
     float color_u = (point1_yuv.y - point2_yuv.y) * (point1_yuv.y - point2_yuv.y);
     float color_v = (point1_yuv.z - point2_yuv.z) * (point1_yuv.z - point2_yuv.z);
     auto color_deviation = static_cast<float>(sqrt(color_y + color_u + color_v));
     return color_deviation;
 }
float Measure::colorErrorYuv (const UncompressedVoxel & v1, const UncompressedVoxel & v2) static
Computes color error between given voxels in YUV space.
Definition at line 126 of file Measure.cpp.
References Encoder::bit8ToRgb(), UncompressedVoxel::color_rgba, and colorErrorYuv().
{
     return colorErrorYuv(
         Encoder::bit8ToRgb(v1.color_rgba),
         Encoder::bit8ToRgb(v2.color_rgba)
     );
 }
float Measure::colorErrorYuvWithoutY (const Vec< float > & point1, const Vec< float > & point2) static
Computes color error in YUV space without taking Y into account. Values should be given in RGB space with component values in range [0,1].
Definition at line 133 of file Measure.cpp.
References Encoder::rgbToYuv(), Vec< C >::y, and Vec< C >::z.
Referenced by colorErrorYuvWithoutY().
 {
     Vec<float> point1_yuv = Encoder::rgbToYuv(point1);
     Vec<float> point2_yuv = Encoder::rgbToYuv(point2);
     float color_u = (point1_yuv.y - point2_yuv.y) * (point1_yuv.y - point2_yuv.y);
     float color_v = (point1_yuv.z - point2_yuv.z) * (point1_yuv.z - point2_yuv.z);
     auto color_deviation = static_cast<float>(sqrt(color_u + color_v));
     return color_deviation;
 }
float Measure::colorErrorYuvWithoutY (const UncompressedVoxel & v1, const UncompressedVoxel & v2) static
Computes color error between given voxels in YUV space without taking Y into account.
Definition at line 146 of file Measure.cpp.
References Encoder::bit8ToRgb(), UncompressedVoxel::color_rgba, and colorErrorYuvWithoutY().
{
     return colorErrorYuvWithoutY(
         Encoder::bit8ToRgb(v1.color_rgba),
         Encoder::bit8ToRgb(v2.color_rgba)
     );
 }
float Measure::colorErrorCielab (const Vec< float > & point1, const Vec< float > & point2) static
Computes color error in Cielab space. Values should be given in RGB space with component values in range [0,1].
Definition at line 173 of file Measure.cpp.
References Encoder::rgbToCieLab(), Vec< C >::x, Vec< C >::y, and Vec< C >::z.
Referenced by colorErrorCielab(), and compare().
{
     //Calculate YUV Color values for point1 and point2
     Vec<float> point1_lab = Encoder::rgbToCieLab(point1);
     Vec<float> point2_lab = Encoder::rgbToCieLab(point2);
     float color_L = (point1_lab.x - point2_lab.x) * (point1_lab.x - point2_lab.x);
     float color_a = (point1_lab.y - point2_lab.y) * (point1_lab.y - point2_lab.y);
     float color_b = (point1_lab.z - point2_lab.z) * (point1_lab.z - point2_lab.z);
     auto color_deviation = static_cast<float>(sqrt(color_L + color_a + color_b));
     return color_deviation;
 }
float Measure::colorErrorCielab (const UncompressedVoxel & v1, const UncompressedVoxel & v2) static
Computes color error between given voxels in Cielab space.
Definition at line 187 of file Measure.cpp.
References Encoder::bit8ToRgb(), UncompressedVoxel::color_rgba, and colorErrorCielab().
{
     return colorErrorCielab(
         Encoder::bit8ToRgb(v1.color_rgba),
         Encoder::bit8ToRgb(v2.color_rgba)
     );
 }
float Measure::colorErrorXyz (const Vec< float > & point1, const Vec< float > & point2) static
Computes color error in XYZ space. Values should be given in RGB space with component values in range [0,1].
Definition at line 153 of file Measure.cpp.
References Encoder::rgbToXyz(), Vec< C >::x, Vec< C >::y, and Vec< C >::z.
Referenced by colorErrorXyz().
{
     Vec<float> point1_lab = Encoder::rgbToXyz(point1);
     Vec<float> point2_lab = Encoder::rgbToXyz(point2);
     float color_x = (point1_lab.x - point2_lab.x) * (point1_lab.x - point2_lab.x);
     float color_y = (point1_lab.y - point2_lab.y) * (point1_lab.y - point2_lab.y);
     float color_z = (point1_lab.z - point2_lab.z) * (point1_lab.z - point2_lab.z);
     auto color_deviation = static_cast<float>(sqrt(color_x + color_y + color_z));
     return color_deviation;
 }
float Measure::colorErrorXyz (const UncompressedVoxel & v1, const UncompressedVoxel & v2) static
Computes color error between given voxels in XYZ space.
Definition at line 166 of file Measure.cpp.
References Encoder::bit8ToRgb(), UncompressedVoxel::color_rgba, and colorErrorXyz().
{
     return colorErrorXyz(
         Encoder::bit8ToRgb(v1.color_rgba),
         Encoder::bit8ToRgb(v2.color_rgba)
     );
 }
float Measure::calcVariance (const std::vector< float > & values) static
Computes variance for values in given std::vector.
Definition at line 194 of file Measure.cpp.
Referenced by compare().
 {
     float avg_error = 0;
     float variance = 0;
     for(auto const& l : values)
         avg_error += l;
     avg_error = avg_error / values.size();
     for(auto const& l : values)
         variance +=  (l - avg_error) * (l - avg_error);
     return variance / values.size();
 }
Member Data Documentation
Measure::TimePoint Measure::start_time_ private
Definition at line 142 of file Measure.hpp.
Referenced by startWatch(), and stopWatch().
The documentation for this class was generated from the following files:
include/Measure.hpp
src/Measure.cpp