libpcc: BitVec Class Reference
BitVec Class Reference
#include <BitVec.hpp>
Public Member Functions
BitVec (uint64_t t_x=0, uint64_t t_y=0, uint64_t t_z=0, BitCount NX=BIT_8, BitCount NY=BIT_8, BitCount NZ=BIT_8)
BitVec (const std::vector< bool > &packed, BitCount NX=BIT_8, BitCount NY=BIT_8, BitCount NZ=BIT_8)
~BitVec ()
void initX (BitCount N, uint64_t val=0)
void initY (BitCount N, uint64_t val=0)
void initZ (BitCount N, uint64_t val=0)
BitCount getNX () const
BitCount getNY () const
BitCount getNZ () const
Vec< uint64_t > const toVecInt64 ()
uint64_t getXInt () const
uint64_t getYInt () const
uint64_t getZInt () const
const AbstractBitValue * getX () const
const AbstractBitValue * getY () const
const AbstractBitValue * getZ () const
void setX (uint64_t x_t)
void setX (size_t i, bool val)
void setY (uint64_t y_t)
void setY (size_t i, bool val)
void setZ (uint64_t z_t)
void setZ (size_t i, bool val)
const std::vector< bool > getPackedBitset () const
void setFromPackedBitset (const std::vector< bool > &packed)
Private Attributes
AbstractBitValue * x_
AbstractBitValue * y_
AbstractBitValue * z_
Detailed Description
Three component vector class providing interface to adjust component precision. Convenience functions offer setting and getting values from/as Vec<uint64_t>.
Definition at line 17 of file BitVec.hpp.
Constructor & Destructor Documentation
BitVec::BitVec (uint64_t t_x = 0, uint64_t t_y = 0, uint64_t t_z = 0, BitCount NX = BIT_8, BitCount NY = BIT_8, BitCount NZ = BIT_8) explicit
Definition at line 3 of file BitVec.cpp.
References initX(), initY(), and initZ().
     : x_(nullptr)
     , y_(nullptr)
     , z_(nullptr)
 {
     initX(NX, t_x);
     initY(NY, t_y);
     initZ(NZ, t_z);
 }
BitVec::BitVec (const std::vector< bool > & packed, BitCount NX = BIT_8, BitCount NY = BIT_8, BitCount NZ = BIT_8) explicit
Definition at line 13 of file BitVec.cpp.
References initX(), initY(), initZ(), and setFromPackedBitset().
     : x_(nullptr)
     , y_(nullptr)
     , z_(nullptr)
 {
     initX(NX);
     initY(NY);
     initZ(NZ);
     setFromPackedBitset(packed);
 }
BitVec::~BitVec ()
Definition at line 24 of file BitVec.cpp.
References x_, y_, and z_.
 {
     delete x_;
     delete y_;
     delete z_;
 }
Member Function Documentation
void BitVec::initX (BitCount N, uint64_t val = 0)
Sets x-component precision of this instance. x value will be set to val after initialization.
Definition at line 31 of file BitVec.cpp.
References initBitValue(), and x_.
Referenced by BitVec().
 {
     initBitValue(x_, N, val);
 }
void BitVec::initY (BitCount N, uint64_t val = 0)
Sets y-component precision of this instance. y value will be set to val after initialization.
Definition at line 36 of file BitVec.cpp.
References initBitValue(), and y_.
Referenced by BitVec().
 {
     initBitValue(y_, N, val);
 }
void BitVec::initZ (BitCount N, uint64_t val = 0)
Sets z-component precision of this instance. z value will be set to val after initialization.
Definition at line 41 of file BitVec.cpp.
References initBitValue(), and z_.
Referenced by BitVec().
 {
     initBitValue(z_, N, val);
 }
BitCount BitVec::getNX () const
Returns x-component precision.
Definition at line 46 of file BitVec.cpp.
References AbstractBitValue::getN(), and x_.
 {
     return x_->getN();
 }
BitCount BitVec::getNY () const
Returns y-component precision.
Definition at line 51 of file BitVec.cpp.
References AbstractBitValue::getN(), and y_.
 {
     return y_->getN();
 }
BitCount BitVec::getNZ () const
Returns z-component precision.
Definition at line 56 of file BitVec.cpp.
References AbstractBitValue::getN(), and z_.
 {
     return z_->getN();
 }
Vec< uint64_t > const BitVec::toVecInt64 ()
Returns x, y, z component vector converted to Vec<uint64_t>.
Definition at line 61 of file BitVec.cpp.
References getXInt(), getYInt(), and getZInt().
 {
     return Vec<uint64_t>(getXInt(), getYInt(), getZInt());
 }
uint64_t BitVec::getXInt () const
Returns x value as uint64_t.
Definition at line 66 of file BitVec.cpp.
References AbstractBitValue::get(), and x_.
Referenced by toVecInt64(), and BitVecArray::unpack().
 {
     return x_->get();
 }
uint64_t BitVec::getYInt () const
Returns y value as uint64_t.
Definition at line 71 of file BitVec.cpp.
References AbstractBitValue::get(), and y_.
Referenced by toVecInt64(), and BitVecArray::unpack().
 {
     return y_->get();
 }
uint64_t BitVec::getZInt () const
Returns z value as uint64_t.
Definition at line 76 of file BitVec.cpp.
References AbstractBitValue::get(), and z_.
Referenced by toVecInt64(), and BitVecArray::unpack().
 {
     return z_->get();
 }
const AbstractBitValue * BitVec::getX () const
Returns x value as const AbstractBitValue*. Exposes interface to reading BITS. see (AbstractBitValue).
Definition at line 136 of file BitVec.cpp.
References x_.
Referenced by BitVecArray::pack().
 {
     return x_;
 }
const AbstractBitValue * BitVec::getY () const
Returns y value as const AbstractBitValue*. Exposes interface to reading BITS. see (AbstractBitValue).
Definition at line 141 of file BitVec.cpp.
References y_.
Referenced by BitVecArray::pack().
{
     return y_;
 }
const AbstractBitValue * BitVec::getZ () const
Returns z value as const AbstractBitValue*. Exposes interface to reading BITS. see (AbstractBitValue).
Definition at line 145 of file BitVec.cpp.
References z_.
Referenced by BitVecArray::pack().
{
     return z_;
 }
void BitVec::setX (uint64_t x_t)
Sets x value from uint64_t.
Definition at line 81 of file BitVec.cpp.
References AbstractBitValue::set(), and x_.
Referenced by BitVecArray::pack(), and BitVecArray::unpack().
 {
     x_->set(x_t);
 }
void BitVec::setX (size_t i, bool val)
Sets ith bit of x value.
Definition at line 86 of file BitVec.cpp.
References AbstractBitValue::setBit(), and x_.
 {
     x_->setBit(i, val);
 }
void BitVec::setY (uint64_t y_t)
Sets y value from uint64_t.
Definition at line 91 of file BitVec.cpp.
References AbstractBitValue::set(), and y_.
Referenced by BitVecArray::pack(), and BitVecArray::unpack().
 {
     y_->set(y_t);
 }
void BitVec::setY (size_t i, bool val)
Sets ith bit of y value.
Definition at line 96 of file BitVec.cpp.
References AbstractBitValue::setBit(), and y_.
 {
     y_->setBit(i, val);
 }
void BitVec::setZ (uint64_t z_t)
Sets z value from uint64_t.
Definition at line 101 of file BitVec.cpp.
References AbstractBitValue::set(), and z_.
Referenced by BitVecArray::pack(), and BitVecArray::unpack().
 {
     z_->set(z_t);
 }
void BitVec::setZ (size_t i, bool val)
Sets ith bit of z value.
Definition at line 106 of file BitVec.cpp.
References AbstractBitValue::setBit(), and z_.
 {
     z_->setBit(i, val);
 }
const std::vector< bool > BitVec::getPackedBitset () const
Returns vector of bool encoded BITS, retrieved by concatenating x, y, z - component BITS. Returned format is [x_0,x_1,...,x_n,y_0,y_1,...,y_n,z_0,z_1,...,z_n]
Definition at line 111 of file BitVec.cpp.
References AbstractBitValue::getBit(), AbstractBitValue::getN(), x_, y_, and z_.
 {
     std::vector<bool> packed;
     packed.resize(x_->getN()+y_->getN()+z_->getN());
     for(size_t i = 0; i < x_->getN(); ++i)
         packed[i] = x_->getBit(i);
     for(size_t i = 0; i < y_->getN(); ++i)
         packed[y_->getN()+i] = y_->getBit(i);
     for(size_t i = 0; i < z_->getN(); ++i)
         packed[x_->getN()+y_->getN()+i] = z_->getBit(i);
     return packed;
 }
void BitVec::setFromPackedBitset (const std::vector< bool > & packed)
Sets component values from vector of bool encoded BITS. Number of elements has to be equal to x,y,z - component precision sum. Format should be [x_0,x_1,...,x_n,y_0,y_1,...,y_n,z_0,z_1,...,z_n].
Definition at line 124 of file BitVec.cpp.
References AbstractBitValue::getN(), AbstractBitValue::setBit(), x_, y_, and z_.
Referenced by BitVec().
 {
     if(packed.size() != x_->getN()+y_->getN()+z_->getN())
         return;
     for(size_t i = 0; i < x_->getN(); ++i)
         x_->setBit(i, packed[i]);
     for(size_t i = 0; i < y_->getN(); ++i)
         y_->setBit(i, packed[x_->getN()+i]);
     for(size_t i = 0; i < z_->getN(); ++i)
         z_->setBit(i, packed[x_->getN()+y_->getN()+i]);
 }
Member Data Documentation
AbstractBitValue* BitVec::x_ private
Definition at line 146 of file BitVec.hpp.
Referenced by getNX(), getPackedBitset(), getX(), getXInt(), initX(), setFromPackedBitset(), setX(), and ~BitVec().
AbstractBitValue* BitVec::y_ private
Definition at line 147 of file BitVec.hpp.
Referenced by getNY(), getPackedBitset(), getY(), getYInt(), initY(), setFromPackedBitset(), setY(), and ~BitVec().
AbstractBitValue* BitVec::z_ private
Definition at line 148 of file BitVec.hpp.
Referenced by getNZ(), getPackedBitset(), getZ(), getZInt(), initZ(), setFromPackedBitset(), setZ(), and ~BitVec().
The documentation for this class was generated from the following files:
include/BitVec.hpp
src/BitVec.cpp