libpcc: CMDParser Class Reference
CMDParser Class Reference
#include <CMDParser.hpp>
Public Member Functions
CMDParser (std::string arguments)
~CMDParser ()
void addOpt (std::string opt, int numValues, std::string optlong, std::string help="")
void showHelp ()
void init (int &argc, char **argv)
int isOptSet (std::string opt)
std::vector< int > getOptsInt (std::string)
std::vector< float > getOptsFloat (std::string)
std::vector< std::string > getOptsString (std::string)
std::vector< std::string > getArgs () const
Private Attributes
std::map< std::string, std::vector< std::string > * > _opts
std::map< std::string, int > _optsNumValues
std::map< std::string, std::string > _optslong
std::vector< std::string > _args
std::string _help
std::string _arguments
Detailed Description
Convenience class to define command line argument interface of a cmd program. Can be used to set options and extract them from a command line call.
Definition at line 13 of file CMDParser.hpp.
Constructor & Destructor Documentation
CMDParser::CMDParser (std::string arguments)
Definition at line 5 of file CMDParser.cpp.
References addOpt().
                                        :
   _opts(),
   _optsNumValues(),
   _optslong(),
   _args(),
   _help(),
   _arguments(arguments){
   addOpt("h", -1,"help" ,/*cchar**/"show this help message and exit");
 }
CMDParser::~CMDParser ()
Definition at line 15 of file CMDParser.cpp.
References _opts.
                      {
   std::map<std::string, std::vector<std::string>* >::iterator optIt = _opts.begin();
   for(; optIt != _opts.end(); ++optIt){
     if((*optIt).second){
       delete (*optIt).second;
     }
   }
 }
Member Function Documentation
void CMDParser::addOpt (std::string opt, int numValues, std::string optlong, std::string help = "")
Definition at line 25 of file CMDParser.cpp.
References _help, _opts, _optslong, and _optsNumValues.
Referenced by CMDParser().
{
   _opts[opt] = 0;
   _optsNumValues[opt] = numValues;
   _optslong[opt] = optlong;
   _help += "\t-" + opt + ", --" + optlong;
   if(numValues>0)
     for (int i=0; i<numValues; ++i)
       _help += " <value>";
   if(numValues == 0)
     _help += " <value0> ... <valueN>";
   _help += "\n\t\t" + help + "\n";
 }
void CMDParser::showHelp ()
Definition at line 44 of file CMDParser.cpp.
References _help.
Referenced by init().
                    {
   std::cout << _help;
   exit(0);
 }
void CMDParser::init (int & argc, char ** argv)
Definition at line 50 of file CMDParser.cpp.
References _args, _arguments, _help, _opts, _optslong, _optsNumValues, and showHelp().
{
   std::string progname = argv[0];
   _help = "usage: " + progname + " [options] " + _arguments + "\n" + "options can be:" + "\n" + _help;
   for(int i = 1; i < argc; ++i){
     std::string arg = argv[i];
     if(arg == "--help" || arg == "-h")
       showHelp();
     int foundArg = 0;
     std::map<std::string, std::vector<std::string>* >::iterator optIt = _opts.begin();
     for(; optIt != _opts.end(); ++optIt){
       if( ("--" + _optslong[(*optIt).first]) == arg || ("-" + (*optIt).first)== arg){
     foundArg = 1;
     int numValues = _optsNumValues[(*optIt).first];
     if(numValues < 0){
       _opts[(*optIt).first] = new std::vector<std::string>;
     }
     else if(numValues > 0){
       _opts[(*optIt).first] = new std::vector<std::string>;
       for(int j = 1; j <= numValues; ++j){
         if(i + j < argc){
           (_opts[(*optIt).first])->push_back(argv[j+i]);
         }
         else
           showHelp();
       }
       i += numValues;
     }
     else{ // arbritraty values not implemented yet
       std::cout << "ERROR: arbritraty values not implemented yet" << std::endl;
       exit(0);
     }
       }
     }
     if(!foundArg)
       _args.push_back(arg);
   }
   if(_args.empty() && (_arguments != ""))
     showHelp();
 }
int CMDParser::isOptSet (std::string opt)
Definition at line 94 of file CMDParser.cpp.
References _opts.
Referenced by getOptsFloat(), getOptsInt(), and getOptsString().
{
   if(_opts[opt] != 0)
     return 1;
   return 0;
 }
std::vector< int > CMDParser::getOptsInt (std::string opt)
Definition at line 101 of file CMDParser.cpp.
References _opts, and isOptSet().
{
   std::vector<int> opts;
   if(isOptSet(opt))
     for(unsigned int i = 0; i < _opts[opt]->size(); ++i)
       opts.push_back(atoi((*_opts[opt])[i].c_str()));
   return opts;
 }
std::vector< float > CMDParser::getOptsFloat (std::string opt)
Definition at line 110 of file CMDParser.cpp.
References _opts, and isOptSet().
{
   std::vector<float> opts;
   if(isOptSet(opt))
     for(unsigned int i = 0; i < _opts[opt]->size(); ++i)
       opts.push_back( (float) atof((*_opts[opt])[i].c_str()));
   return opts;
 }
std::vector< std::string > CMDParser::getOptsString (std::string opt)
Definition at line 119 of file CMDParser.cpp.
References _opts, and isOptSet().
{
   std::vector<std::string> opts;
   if(isOptSet(opt))
     for(unsigned int i = 0; i < _opts[opt]->size(); ++i)
       opts.push_back((*_opts[opt])[i]);
   return opts;
 }
std::vector< std::string > CMDParser::getArgs () const
Definition at line 128 of file CMDParser.cpp.
References _args.
{
   return _args;
 }
Member Data Documentation
std::map<std::string,std::vector<std::string>* > CMDParser::_opts private
Definition at line 32 of file CMDParser.hpp.
Referenced by addOpt(), getOptsFloat(), getOptsInt(), getOptsString(), init(), isOptSet(), and ~CMDParser().
std::map<std::string,int> CMDParser::_optsNumValues private
Definition at line 33 of file CMDParser.hpp.
Referenced by addOpt(), and init().
std::map<std::string,std::string> CMDParser::_optslong private
Definition at line 34 of file CMDParser.hpp.
Referenced by addOpt(), and init().
std::vector<std::string> CMDParser::_args private
Definition at line 35 of file CMDParser.hpp.
Referenced by getArgs(), and init().
std::string CMDParser::_help private
Definition at line 36 of file CMDParser.hpp.
Referenced by addOpt(), init(), and showHelp().
std::string CMDParser::_arguments private
Definition at line 37 of file CMDParser.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
include/CMDParser.hpp
src/CMDParser.cpp