libpcc: AbstractBitValue Struct Reference
AbstractBitValue Struct Reference abstract
#include <BitValue.hpp>
Public Member Functions
virtual BitCount getN () const =0
virtual uint64_t get () const =0
virtual void set (uint64_t)=0
virtual bool getBit (size_t pos) const =0
virtual void setBit (size_t pos, bool val)=0
Detailed Description
Defines base interface for all BitValues. initBitValue (Helper function) can be called for generic child class instantiation.
Definition at line 51 of file BitValue.hpp.
Member Function Documentation
virtual BitCount AbstractBitValue::getN () const pure virtual
Implemented in BitValue< N >.
Referenced by BitVec::getNX(), BitVec::getNY(), BitVec::getNZ(), BitVec::getPackedBitset(), initBitValue(), and BitVec::setFromPackedBitset().
virtual uint64_t AbstractBitValue::get () const pure virtual
Implemented in BitValue< N >.
Referenced by BitVec::getXInt(), BitVec::getYInt(), and BitVec::getZInt().
virtual void AbstractBitValue::set (uint64_t) pure virtual
Implemented in BitValue< N >.
Referenced by initBitValue(), BitVec::setX(), BitVec::setY(), and BitVec::setZ().
virtual bool AbstractBitValue::getBit (size_t pos) const pure virtual
Implemented in BitValue< N >.
Referenced by BitVec::getPackedBitset(), and BitVecArray::pack().
virtual void AbstractBitValue::setBit (size_t pos, bool val) pure virtual
Implemented in BitValue< N >.
Referenced by BitVec::setFromPackedBitset(), BitVec::setX(), BitVec::setY(), and BitVec::setZ().
The documentation for this struct was generated from the following file:
include/BitValue.hpp