libpcc: BoundingBox Struct Reference
BoundingBox Struct Reference
#include <BoundingBox.hpp>
Public Member Functions
BoundingBox (float x_min_t=.0f, float x_max_t=.0f, float y_min_t=.0f, float y_max_t=.0f, float z_min_t=.0f, float z_max_t=.0f)
BoundingBox (const Vec< float > &min_t, const Vec< float > &max_t)
BoundingBox (BoundingBox const &bb)=default
~BoundingBox ()=default
bool contains (Vec< float > const &v) const
bool contains (const float v[3]) const
bool contains (const UncompressedVoxel &v) const
Vec< float > const calcRange () const
Public Attributes
Vec< float > min
Vec< float > max
Detailed Description
Data transfer object encoding a 3D bounding box.
Definition at line 10 of file BoundingBox.hpp.
Constructor & Destructor Documentation
BoundingBox::BoundingBox (float x_min_t = .0f, float x_max_t = .0f, float y_min_t = .0f, float y_max_t = .0f, float z_min_t = .0f, float z_max_t = .0f) inline explicit
Definition at line 11 of file BoundingBox.hpp.
Referenced by BoundingBox().
         : min(x_min_t, y_min_t, z_min_t)
         , max(x_max_t, y_max_t, z_max_t)
     {}
BoundingBox::BoundingBox (const Vec< float > & min_t, const Vec< float > & max_t) inline explicit
Definition at line 16 of file BoundingBox.hpp.
References BoundingBox(), and ~BoundingBox().
         : min(min_t)
         , max(max_t)
     {}
BoundingBox::BoundingBox (BoundingBox const & bb) default
BoundingBox::~BoundingBox () default
Referenced by BoundingBox().
Member Function Documentation
bool BoundingBox::contains (Vec< float > const & v) const inline
Returns true if given Vec<float> is contained inside volume defined by this instance. false otherwise.
Definition at line 29 of file BoundingBox.hpp.
References max, min, Vec< C >::x, Vec< C >::y, and Vec< C >::z.
Referenced by PointCloudGridEncoder::buildPointCloudGrid(), Measure::compare(), and contains().
     {
         return v.x > min.x && v.x < max.x &&
                v.y > min.y && v.y < max.y &&
                v.z > min.z && v.z < max.z;
     }
bool BoundingBox::contains (const float v[3]) const inline
Returns true if given const float[3] is contained inside volume defined by this instance. false otherwise.
Definition at line 40 of file BoundingBox.hpp.
References max, min, Vec< C >::x, Vec< C >::y, and Vec< C >::z.
     {
         return v[0] > min.x && v[0] < max.x &&
                v[1] > min.y && v[1] < max.y &&
                v[2] > min.z && v[2] < max.z;
     }
bool BoundingBox::contains (const UncompressedVoxel & v) const inline
Returns true if given UncompressedVoxel is contained inside volume defined by this instance. false otherwise.
Definition at line 51 of file BoundingBox.hpp.
References contains(), and UncompressedVoxel::pos.
     {
         return contains(v.pos);
     }
Vec<float> const BoundingBox::calcRange () const inline
Returns Vec<float> denoting length of x, y & z - axis spun by this instance.
Definition at line 60 of file BoundingBox.hpp.
References max, and min.
Referenced by PointCloudGridEncoder::buildPointCloudGrid(), and PointCloudGridEncoder::extractPointCloudFromGrid().
{
         return max - min;
     }
Member Data Documentation
Vec<float> BoundingBox::min
Definition at line 64 of file BoundingBox.hpp.
Referenced by PointCloudGridEncoder::calcGridCellIndex(), calcRange(), contains(), PointCloudGridEncoder::decodeGridHeader(), PointCloudGridEncoder::encodeGridHeader(), PointCloudGridEncoder::extractPointCloudFromGrid(), PointCloudGridEncoder::EncodingSettings::getQuantizationStepSize(), PointCloudGridEncoder::mapToCell(), Encoder::mapVec(), Encoder::mapVecToFloat(), and PointCloudGridEncoder::GridHeader::toString().
Vec<float> BoundingBox::max
Definition at line 65 of file BoundingBox.hpp.
Referenced by calcRange(), contains(), PointCloudGridEncoder::decodeGridHeader(), PointCloudGridEncoder::encodeGridHeader(), PointCloudGridEncoder::EncodingSettings::getQuantizationStepSize(), Encoder::mapVec(), Encoder::mapVecToFloat(), and PointCloudGridEncoder::GridHeader::toString().
The documentation for this struct was generated from the following file:
include/BoundingBox.hpp