libpcc: PointCloudGridEncoder::CellHeader Struct Reference
PointCloudGridEncoder::CellHeader Struct Reference
Public Member Functions
const std::string toString () const
Static Public Member Functions
static size_t getByteSize ()
Public Attributes
unsigned cell_idx
BitCount point_encoding_x
BitCount point_encoding_y
BitCount point_encoding_z
BitCount color_encoding_x
BitCount color_encoding_y
BitCount color_encoding_z
unsigned num_elements
Detailed Description
Data transfer object for encoding meta info about a GridCell in a PointCloudGrid.
Definition at line 165 of file PointCloudGridEncoder.hpp.
Member Function Documentation
static size_t PointCloudGridEncoder::CellHeader::getByteSize () inline static
Definition at line 176 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::calcMessageSize(), PointCloudGridEncoder::decodePointCloudGrid(), and PointCloudGridEncoder::encodePointCloudGrid().
         {
             return 1*sizeof(unsigned)+6*sizeof(BitCount);
         }
const std::string PointCloudGridEncoder::CellHeader::toString () const inline
Definition at line 181 of file PointCloudGridEncoder.hpp.
References PointCloudGridEncoder::buildPointCloudGrid(), PointCloudGridEncoder::calcGridCellIndex(), PointCloudGridEncoder::calcMessageSize(), PointCloudGridEncoder::decode(), PointCloudGridEncoder::decodeBlackList(), PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::decodeCellHeader(), PointCloudGridEncoder::decodeGlobalHeader(), PointCloudGridEncoder::decodeGridHeader(), PointCloudGridEncoder::decodePointCloudGrid(), PointCloudGridEncoder::encode(), PointCloudGridEncoder::encodeBlackList(), PointCloudGridEncoder::encodeCell(), PointCloudGridEncoder::encodeCellHeader(), PointCloudGridEncoder::encodeGlobalHeader(), PointCloudGridEncoder::encodeGridHeader(), PointCloudGridEncoder::encodePointCloudGrid(), PointCloudGridEncoder::EncodingSettings::EncodingSettings(), PointCloudGridEncoder::entropyCompression(), PointCloudGridEncoder::entropyDecompression(), PointCloudGridEncoder::extractPointCloudFromGrid(), PointCloudGridEncoder::finalizeMessage(), PointCloudGridEncoder::getPointCloudGrid(), PointCloudGridEncoder::mapToCell(), PointCloudGridEncoder::PointCloudGridEncoder(), PointCloudGridEncoder::readFromAppendix(), PointCloudGridEncoder::writeToAppendix(), and PointCloudGridEncoder::~PointCloudGridEncoder().
         {
             std::stringstream ss;
             ss << "CellHeader(c_idx=" << cell_idx << ", ";
             ss << "p_enc_x=" << point_encoding_x << ", ";
             ss << "p_enc_y=" << point_encoding_y << ", ";
             ss << "p_enc_z=" << point_encoding_z << ", ";
             ss << "c_enc_x=" << color_encoding_x << ", ";
             ss << "c_enc_y=" << color_encoding_y << ", ";
             ss << "c_enc_z=" << color_encoding_z << ", ";
             ss << "num_elmts=" << num_elements << ")";
             return ss.str();
         }
Member Data Documentation
unsigned PointCloudGridEncoder::CellHeader::cell_idx
Definition at line 166 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::decodeCell(), and PointCloudGridEncoder::encodePointCloudGrid().
BitCount PointCloudGridEncoder::CellHeader::point_encoding_x
Definition at line 168 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::decodeCellHeader(), and PointCloudGridEncoder::encodeCellHeader().
BitCount PointCloudGridEncoder::CellHeader::point_encoding_y
Definition at line 169 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::decodeCellHeader(), and PointCloudGridEncoder::encodeCellHeader().
BitCount PointCloudGridEncoder::CellHeader::point_encoding_z
Definition at line 170 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::decodeCellHeader(), and PointCloudGridEncoder::encodeCellHeader().
BitCount PointCloudGridEncoder::CellHeader::color_encoding_x
Definition at line 171 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::decodeCellHeader(), and PointCloudGridEncoder::encodeCellHeader().
BitCount PointCloudGridEncoder::CellHeader::color_encoding_y
Definition at line 172 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::decodeCellHeader(), and PointCloudGridEncoder::encodeCellHeader().
BitCount PointCloudGridEncoder::CellHeader::color_encoding_z
Definition at line 173 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::decodeCellHeader(), and PointCloudGridEncoder::encodeCellHeader().
unsigned PointCloudGridEncoder::CellHeader::num_elements
Definition at line 174 of file PointCloudGridEncoder.hpp.
Referenced by PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::decodeCellHeader(), and PointCloudGridEncoder::encodeCellHeader().
The documentation for this struct was generated from the following file:
include/PointCloudGridEncoder.hpp