libpcc: GridCell Struct Reference
GridCell Struct Reference
#include <PointCloudGrid.hpp>
Public Member Functions
GridCell ()=default
~GridCell ()=default
void initPoints (BitCount NX, BitCount NY, BitCount NZ)
void initColors (BitCount NX, BitCount NY, BitCount NZ)
void addVoxel (const Vec< uint64_t > &p, const Vec< uint64_t > &c)
unsigned size ()
void resize (unsigned s)
void clear ()
Public Attributes
BitVecArray points
BitVecArray colors
Detailed Description
Data transfer object defining a cell within a PointCloudGrid. a BitVecArray is used as the container type for both points and colors. Convenience functions are provided for initialization of point and color component bit counts and basic container interaction.
Definition at line 12 of file PointCloudGrid.hpp.
Constructor & Destructor Documentation
GridCell::GridCell () default
GridCell::~GridCell () default
Member Function Documentation
void GridCell::initPoints (BitCount NX, BitCount NY, BitCount NZ) inline
Definition at line 17 of file PointCloudGrid.hpp.
References BitVecArray::init(), and points.
Referenced by PointCloudGridEncoder::decodeCell().
     {
         points.init(NX, NY, NZ);
     }
void GridCell::initColors (BitCount NX, BitCount NY, BitCount NZ) inline
Definition at line 22 of file PointCloudGrid.hpp.
References colors, and BitVecArray::init().
Referenced by PointCloudGridEncoder::decodeCell().
     {
         colors.init(NX, NY, NZ);
     }
void GridCell::addVoxel (const Vec< uint64_t > & p, const Vec< uint64_t > & c) inline
Definition at line 27 of file PointCloudGrid.hpp.
References colors, BitVecArray::emplace_back(), points, Vec< C >::x, Vec< C >::y, and Vec< C >::z.
     {
         points.emplace_back(p.x, p.y, p.z);
         colors.emplace_back(c.x, c.y, c.z);
     }
unsigned GridCell::size () inline
Definition at line 33 of file PointCloudGrid.hpp.
References points, and BitVecArray::size().
Referenced by PointCloudGridEncoder::encodeCell(), and PointCloudGridEncoder::extractPointCloudFromGrid().
     {
         return points.size();
     }
void GridCell::resize (unsigned s) inline
Definition at line 38 of file PointCloudGrid.hpp.
References colors, points, and BitVecArray::resize().
     {
         points.resize(s);
         colors.resize(s);
     }
void GridCell::clear () inline
Definition at line 44 of file PointCloudGrid.hpp.
References BitVecArray::clear(), colors, and points.
Referenced by PointCloudGrid::resize().
     {
         points.clear();
         colors.clear();
     }
Member Data Documentation
BitVecArray GridCell::points
Definition at line 50 of file PointCloudGrid.hpp.
Referenced by addVoxel(), clear(), PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::encodeCell(), PointCloudGridEncoder::extractPointCloudFromGrid(), PointCloudGrid::getQuantizationStepSize(), initPoints(), resize(), and size().
BitVecArray GridCell::colors
Definition at line 51 of file PointCloudGrid.hpp.
Referenced by addVoxel(), clear(), PointCloudGridEncoder::decodeCell(), PointCloudGridEncoder::encodeCell(), PointCloudGridEncoder::extractPointCloudFromGrid(), initColors(), and resize().
The documentation for this struct was generated from the following file:
include/PointCloudGrid.hpp